Dh\BlogBundle\Entity\BlogPostImageUrl:
    type: entity
    table: null
    repositoryClass: Dh\BlogBundle\Repository\BlogPostImageUrlRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        imgUrl:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
