Dh\BlogBundle\Entity\BlogPostEntity:
    type: entity
    table: null
    repositoryClass: Dh\BlogBundle\Repository\BlogPostEntityRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        content:
            type: text
        category:
            type: string
            length: 255
            nullable: true
        date:
            type: datetime
        imgurl:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
