dh_blog:
    resource: "@DhBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

dh_main:
    resource: "@DhMainBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
