<?php

namespace Dh\BlogBundle\Repository;

/**
 * BlogPostEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogPostEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
