<?php

namespace Dh\BlogBundle\Repository;

/**
 * BlogEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
