<?php

namespace Dh\BlogBundle\Repository;

/**
 * BlogPostImageUrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogPostImageUrlRepository extends \Doctrine\ORM\EntityRepository
{
}
